--function onCreate()
--    setPropertyFromClass('openfl.Lib', 'application.window.title', 'egg man')
--
--    debugPrint('                ' .. getPropertyFromClass('openfl.Lib', 'application.window.parameters'))
--end